# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SfnXXk1hYNT3Em8V5HlpCWa3Vuf50g5b
"""

import numpy as np
x = np.array([0,1,2,3,4,5,6,7,8])
y = np.array([1,2,3,5,4,6,8,7,9])
coeffs =  np.polyfit(x,y,1)
print(coeffs)

m = coeffs[0]
b = coeffs[1]
esty = (m * x)+ b

import matplotlib.pyplot as plt
plt.plot(x, esty)
plt.scatter(x, y)
plt.show()